# use containers
sudo: false

os:
  - linux
  - osx

language: cpp

compiler:
  - clang

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then wget --no-check-certificate https://cmake.org/files/v3.4/cmake-3.4.0-rc1-Linux-x86_64.sh; sh cmake-3.4.0-rc1-Linux-x86_64.sh --skip-license --prefix=${HOME}; export PATH=$HOME/bin/:$PATH; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ];  then echo "need cmake 3.2"; fi
  - mkdir antsbin
  - cd antsbin
script:
  - cmake -DRUN_LONG_TESTS=OFF -DRUN_SHORT_TESTS=ON ./.. && make -j 2 && cd ANTS-build/ && make test
notifications:
  email:
    recipients:
      - arman.eshaghi@gmail.com
      - stnava@gmail.com
      - ntustison@gmail.com
